version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install maven -y
      - mvn --version

  pre_build:
    commands:
      - sudo apt get update 
      - sudo apt get install mvn -y
      - echo Running unit tests
      - mvn test

  build:
    commands:
      - echo Building application
      - mvn package -DskipTests=true

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing deployment artifacts

artifacts:
  files:
    - target/*.jar              # Your build output JAR
    - appspec.yml               # Needed for CodeDeploy
    - scripts/**                # Any CodeDeploy hook scripts
  discard-paths: no
