version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # Choose corretto8 or corretto17 as needed
    commands:
      - echo Installing dependencies
      - mvn clean install -DskipTests=true

  pre_build:
    commands:
      - sudo apt get update 
      - sudo apt get install mvn -y
      - echo Running unit tests
      - mvn test

  build:
    commands:
      - echo Building application
      - mvn package -DskipTests=true

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing deployment artifacts

artifacts:
  files:
    - target/*.jar              # Your build output JAR
    - appspec.yml               # Needed for CodeDeploy
    - scripts/**                # Any CodeDeploy hook scripts
  discard-paths: no
